# Generated by Django 6.0.4 on 2026-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationattempt',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationprovider',
            name='auth_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='integrationsyncjob',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationsyncjob',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhookinboxevent',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhookinboxevent',
            name='processing_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
