# Generated by Django 6.0.4 on 2026-04-30 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(db_index=True, default='Assigned', max_length=80)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_assignments', to='Users.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(db_index=True, default='Submitted', max_length=80)),
                ('answer_payload', models.JSONField(blank=True, default=dict)),
                ('evaluated_payload', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Assesment.assessmentassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=220)),
                ('assessment_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=80)),
                ('instructions', models.TextField(blank=True)),
                ('question_payload', models.JSONField(blank=True, default=list)),
                ('passing_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', 'title'],
            },
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='Assesment.assessmenttemplate'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='Assesment_a_tenant__b16663_idx'),
        ),
    ]
