# Generated by Django 6.0.4 on 2026-04-30 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0001_initial'),
        ('EnterpriseCore', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('activity_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='assessmentassignment',
            options={'ordering': ['tenant_id', 'employee_id', '-assigned_at']},
        ),
        migrations.AlterModelOptions(
            name='assessmenttemplate',
            options={'ordering': ['tenant_id', 'department_id', 'sequence_number', 'title']},
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='assessment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='assigned_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='external_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='is_pass',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='note',
            field=models.CharField(db_index=True, default='Incomplete', max_length=120),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmentassignment',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='passed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='provider_attempt_id',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_templates', to='Users.department'),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='provider_template_id',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sequence_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='source_system',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='assessmentassignment',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('LinkGenerated', 'Link Generated'), ('Sent', 'Sent'), ('InProgress', 'In Progress'), ('Submitted', 'Submitted'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], db_index=True, default='Assigned', max_length=80),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=80),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['tenant', 'assessment', 'status'], name='Assesment_a_tenant__bd8ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['tenant', 'due_at', 'status'], name='Assesment_a_tenant__99cf85_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'assessment', 'employee', 'assigned_at'), name='assesment_assignment_once_at_time'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.UniqueConstraint(fields=('tenant', 'assignment', 'attempt_number'), name='assesment_submission_attempt_once'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant', 'code'), name='assesment_template_code_per_tenant'),
        ),
        migrations.AddField(
            model_name='assessmentactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentactivity',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Assesment.assessmentassignment'),
        ),
        migrations.AddField(
            model_name='assessmentactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentactivity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant'),
        ),
        migrations.AddField(
            model_name='assessmentactivity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentactivity',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace'),
        ),
        migrations.AddIndex(
            model_name='assessmentactivity',
            index=models.Index(fields=['tenant', 'activity_type', 'created_at'], name='Assesment_a_tenant__94cfb9_idx'),
        ),
    ]
