# Generated by Django 6.0.4 on 2026-04-30 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('Project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceassignment',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='complianceassignment',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='compliancecampaign',
            name='content_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='file_id',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='deliverymilestone',
            name='bounty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverymilestone',
            name='delayed_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectworkspace',
            name='anti_phishing_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projectworkspace',
            name='clickup_sync_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projectworkspace',
            name='github_organization',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectworkspace',
            name='priority',
            field=models.CharField(db_index=True, default='P2', max_length=40),
        ),
        migrations.AddField(
            model_name='projectworkspace',
            name='project_type',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='projectworkspace',
            name='terms_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='repositorylink',
            name='access_status',
            field=models.CharField(db_index=True, default='Linked', max_length=80),
        ),
        migrations.AddField(
            model_name='repositorylink',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=260),
        ),
        migrations.AddField(
            model_name='repositorylink',
            name='owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='absent_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='github_access_status',
            field=models.CharField(db_index=True, default='NotRequested', max_length=80),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='is_absent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MilestoneComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=180)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='Open', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_components', to='Project.projectworkspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', 'project_id', 'sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='deliverymilestone',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='Project.milestonecomponent'),
        ),
        migrations.CreateModel(
            name='DefaultCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=220)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('project_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('bounty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', 'project_type', 'sequence', 'title'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'project_type', 'title'), name='project_default_checkpoint_once')],
            },
        ),
    ]
