# Generated by Django 5.2.11 on 2026-05-17 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('Project', '0007_add_project_delay_relations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectdelay',
            new_name='Project_pro_tenant__73b547_idx',
            old_name='Project_pro_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='projectdelay',
            new_name='Project_pro_tenant__764d85_idx',
            old_name='Project_pro_tenant_2_idx',
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='role_and_budget',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant'),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace'),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant'),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace'),
        ),
        migrations.AlterField(
            model_name='teamassignmenthistory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teamassignmenthistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant'),
        ),
        migrations.AlterField(
            model_name='teamassignmenthistory',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace'),
        ),
        migrations.AlterField(
            model_name='userrepositorystatus',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userrepositorystatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant'),
        ),
        migrations.AlterField(
            model_name='userrepositorystatus',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace'),
        ),
    ]
