# Generated by Django 6.0.4 on 2026-04-30 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('HtmlTemplate', '0001_initial'),
        ('Users', '0002_department_base_pay_department_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=300)),
                ('macro', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['tenant_id', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='generichtmltemplate',
            options={'ordering': ['tenant_id', 'offer_domain', 'offer_type', 'position']},
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='html_templates', to='Users.department'),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='email_subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='email_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='offer_domain',
            field=models.CharField(db_index=True, default='ATG', max_length=40),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='offer_type',
            field=models.CharField(db_index=True, default='Intern', max_length=40),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generichtmltemplate',
            name='offer_domain',
            field=models.CharField(db_index=True, default='ATG', max_length=40),
        ),
        migrations.AddField(
            model_name='generichtmltemplate',
            name='offer_html_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generichtmltemplate',
            name='offer_type',
            field=models.CharField(db_index=True, default='Intern', max_length=40),
        ),
        migrations.AddField(
            model_name='generichtmltemplate',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='generichtmltemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_templates', to='HtmlTemplate.contenttemplate'),
        ),
        migrations.AddConstraint(
            model_name='generichtmltemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'offer_domain', 'offer_type', 'position'), name='html_generic_offer_once'),
        ),
        migrations.AddField(
            model_name='offermacro',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermacro',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant'),
        ),
        migrations.AddField(
            model_name='offermacro',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermacro',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace'),
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='macros',
            field=models.ManyToManyField(blank=True, related_name='templates', to='HtmlTemplate.offermacro'),
        ),
        migrations.AddConstraint(
            model_name='offermacro',
            constraint=models.UniqueConstraint(fields=('tenant', 'macro'), name='html_offer_macro_per_tenant'),
        ),
    ]
