# Generated by Django 6.0.4 on 2026-04-30 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_system', models.CharField(blank=True, db_index=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('external_url', models.URLField(blank=True)),
                ('external_payload', models.JSONField(blank=True, default=dict)),
                ('company_name', models.CharField(max_length=220)),
                ('source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('stage', models.CharField(db_index=True, default='New', max_length=100)),
                ('priority', models.CharField(db_index=True, default='Normal', max_length=40)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_leads', to='Users.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_system', models.CharField(blank=True, db_index=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('external_url', models.URLField(blank=True)),
                ('external_payload', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=220)),
                ('status', models.CharField(db_index=True, default='Open', max_length=80)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='Banao.leadaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('activity_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=220)),
                ('note', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to='Users.employeeprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Banao.leadaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Banao.leadaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', 'lead_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='Banao.leadtag'),
        ),
        migrations.CreateModel(
            name='ProposalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_system', models.CharField(blank=True, db_index=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('external_url', models.URLField(blank=True)),
                ('external_payload', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=220)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='Banao.leadaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('from_stage', models.CharField(blank=True, max_length=100)),
                ('to_stage', models.CharField(db_index=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_stage_changes', to='Users.employeeprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='Banao.leadaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='leadtag',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='banao_lead_tag_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='leadaccount',
            index=models.Index(fields=['tenant', 'stage', 'owner'], name='Banao_leada_tenant__de7afa_idx'),
        ),
    ]
