# Generated by Django 6.0.4 on 2026-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubExtension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchreviewerassignment',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branchreviewerassignment',
            name='is_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchreviewerassignment',
            name='is_pass',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branchreviewerassignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchtestingassignment',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branchtestingassignment',
            name='is_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchtestingassignment',
            name='is_pass',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branchtestingassignment',
            name='test_report_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='branchtestingassignment',
            name='tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
