# Generated By Django 6.0.4 On 2026-04-30 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=180)),
                ('principal_key', models.CharField(max_length=160)),
                ('status', models.CharField(db_index=True, default='Active', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agent_principals', to='Users.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DraftAgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action_type', models.CharField(db_index=True, max_length=160)),
                ('target_resource_type', models.CharField(db_index=True, max_length=120)),
                ('target_resource_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('approval_payload', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_actions', to='McpAccessLayer.agentprincipal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpResourceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120)),
                ('owning_module', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('resource_schema', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='McpToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120)),
                ('owning_module', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_mutating', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(db_index=True, default='Draft', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='McpInvocationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action', models.CharField(db_index=True, max_length=160)),
                ('decision', models.CharField(db_index=True, max_length=80)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocation_audits', to='McpAccessLayer.agentprincipal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocation_audits', to='McpAccessLayer.mcpresourcedefinition')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocation_audits', to='McpAccessLayer.mcptooldefinition')),
            ],
            options={
                'ordering': ['tenant_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('permission', models.CharField(default='Read', max_length=80)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='McpAccessLayer.agentprincipal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='McpAccessLayer.mcpresourcedefinition')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='McpAccessLayer.mcptooldefinition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentprincipal',
            constraint=models.UniqueConstraint(fields=('tenant', 'principal_key'), name='mcp_agent_principal_key_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='mcpresourcedefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mcp_resource_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='mcptooldefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mcp_tool_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='mcpaccessgrant',
            index=models.Index(fields=['tenant', 'agent', 'permission'], name='McpAccessLa_tenant__7bd8b5_idx'),
        ),
    ]
