# Generated by Django 6.0.4 on 2026-05-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AtgDocs", "0002_drivefolder_drivefile_documentversion_and_more"),
        ("Users", "0002_department_base_pay_department_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="department",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_documents", to="Users.department"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("authenticated", "Authenticated User"), ("link", "Anyone with the Link")],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]