# Generated by Django 6.0.4 on 2026-04-30 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('LegacyBridge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyapplicationmap',
            name='route_prefix',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='legacymodelcrosswalk',
            name='direction',
            field=models.CharField(db_index=True, default='LegacyToBackend', max_length=40),
        ),
        migrations.AddField(
            model_name='legacymodelcrosswalk',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacymodelcrosswalk',
            name='sync_status',
            field=models.CharField(db_index=True, default='Synced', max_length=80),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='dry_run',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='migrated_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='mode',
            field=models.CharField(db_index=True, default='Preview', max_length=80),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='skipped_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LegacyMigrationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('severity', models.CharField(db_index=True, default='Warning', max_length=40)),
                ('source_app_label', models.CharField(db_index=True, max_length=120)),
                ('legacy_model_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('legacy_object_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('message', models.TextField()),
                ('resolution_status', models.CharField(db_index=True, default='Open', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('migration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='LegacyBridge.migrationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnterpriseCore.workspace')),
            ],
            options={
                'ordering': ['tenant_id', 'severity', 'created_at'],
            },
        ),
    ]
