# Generated by Django 6.0.4 on 2026-04-30 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseCore', '0001_initial'),
        ('Git', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitrepositorysnapshot',
            options={'ordering': ['tenant_id', 'organization', 'repository_name']},
        ),
        migrations.AddField(
            model_name='gitrepositorysnapshot',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='gitrepositorysnapshot',
            name='repository_full_name',
            field=models.CharField(blank=True, db_index=True, max_length=260),
        ),
        migrations.AddField(
            model_name='repositoryutilityrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repositoryutilityrequest',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='gitrepositorysnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'organization', 'repository_name'), name='git_repo_snapshot_once'),
        ),
    ]
